openapi: 3.0.0
info:
  title: Gateway Service API
  description: REST API façade for the backend services.
  version: '0.1'
servers:
  - url: http://localhost:5005
    description: Test server
paths:

  /api/exchangeToken:
    get:
      summary: Returns a jwt token
      parameters:
        - in: query
          name: authorizationCode
          schema:
            type: string
          required: true
        - in: query
          name: state
          schema:
            type: string
          required: true
      responses:
        '200':
          description: The jwt token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'

  /api/introspectToken:
    get:
      summary: Returns the token introspection
      responses:
        '200':
          description: The jwt token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntrospectToken'

  /api/gatewayMessage:
    get:
      summary: Returns the gateway information
      responses:
        '200':
          description: The gateway information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayMessage'
components:
  schemas:

    IntrospectToken:
      type: object
      description: Values from token introspection
      properties:
        sub:
          type: string
          description: The subject
        scope:
          type: string
          description: The token scope
        active:
          type: boolean
          description: True if the token is active.
        exp:
          type: string
          format: date-time

    JwtToken:
      type: object
      description: Unencoded JWT toekn
      properties:
        id:
          type: string
          description: The UUID of the the host record.
        access_token:
          type: string
          description: JWT access toekn
        token_type:
          type: string
          description: The type of access token
        expires_in:
          type: number
          description: Token expiration
        refresh_token:
          type: string
          description: The referesh token
        scope:
          type: string
          description: The token scope

    GatewayMessage:
      type: object
      description: Gateway Info
      properties:
        version:
          type: number
          description: The gateway version
        message:
          type: string
          description: The gateway message
