---

server:
  port: 5005

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:5000/.well-known/jwks.json
    client:
      client-id: gateway-client
      client-secret: client-secret

spring:
  profiles:
    active: development
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:5000/.well-known/jwks.json

logging:
  level:
    ROOT: ERROR
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

resource-client-id: gateway-client
resource-client-secret: client-secret
authorization-server-url: http://localhost:5000


