---

server:
  port: 5005

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5000/authentication-service/auth/realms/example
  profiles:
    active: development

logging:
  level:
    ROOT: ERROR
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  packagesToScan: com.example.gateway.api

resource-client-id: gateway-client
resource-client-secret: client-secret
authorization-server-url: http://localhost:5000


