---

server:
  port: 5005

spring:
  profiles:
    active: development
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
    filter:
      order: -100

logging:
  level:
    ROOT: ERROR
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

resource-client-id: gateway-client
resource-client-secret: client-secret
authorization-server-url: http://localhost:8090


