openapi: 3.0.0
info:
  title: Gateway Service API
  description: REST API façade for the backend services.
  version: '0.1'
servers:
  - url: http://localhost:5005
    description: Test server
paths:
  /api/exchangeToken:
    get:
      summary: Returns a jwt token
      responses:
        '200':
          description: The jwt token
          content:
            text/plain:
              schema:
                type: string


