---
server:
  port: 5000

spring:
  profiles:
    active: default
  ldap:
    embedded:
      base-dn: dc=example,dc=com
      ldif: classpath:bootstrap.ldif
      validation:
        enabled: false
      port: 8389

logging:
  level:
    ROOT: ERROR
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

  security:
    oauth2:
      client:
        client-id: gateway-client
        client-secret: client-secret
