---
server:
  port: 5000

spring:
  application:
    name: authentication-service
  profiles:
    active: default
  ldap:
    embedded:
      base-dn: dc=example,dc=com
      ldif: classpath:bootstrap.ldif
      validation:
        enabled: false
      port: 8389
management:
  endpoints:
    web:
      exposure:
        include: '*'
